FROM vaggeliskls/ray-base:latest

ARG RAY_VERSION=2.32.0
RUN pip install --no-cache-dir --upgrade pip setuptools ray[all]==${RAY_VERSION}

# remove pip
# RUN pip uninstall pip -y

# When we move these args with workdir before the build fails
# Non root user configuration
# uid=1000(ray) gid=100(users) groups=100(users), 27(sudo)
ARG UNAME=ray
ARG GNAME=users
ARG UID=1000
ARG GID=0
ARG HOME_DIR=/home/$UNAME
ARG APP_DIR=/app

WORKDIR ${APP_DIR}

# Create a non-root user and app dir
ENV PATH="/root/.local/bin:/opt/conda/bin:$HOME_DIR/.local/bin:$PATH"
ENV HOME=$HOME_DIR
RUN groupadd -f --gid ${GID} ${GNAME} \
    && useradd --uid ${UID} --gid ${GNAME} --home-dir ${HOME_DIR} --create-home --shell /bin/bash ${UNAME} \
    && mkdir -p ${APP_DIR} \
    && chown -R $UNAME:$GNAME ${APP_DIR} \
    && chgrp -R ${GID} ${HOME} \
    && chmod -R g=u ${HOME} 

# switch to non root user 
USER $UNAME
# ENTRYPOINT []
# CMD []
