ARG PYTHON_VERSION=3.10.13
FROM debian:bullseye-slim

LABEL org.opencontainers.image.authors="vaggeliskls"
LABEL org.opencontainers.image.description="A minified version of ray images"

# install packages
RUN apt-get update && apt-get install -y \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Detect the architecture and download the appropriate Miniconda installer
ARG DEFAULT_MINICONDA_URL=https://repo.anaconda.com/miniconda/Miniconda3-py310_24.5.0-0-Linux
RUN ARCH=$(uname -m) && \
    if [ "$ARCH" = "x86_64" ]; then \
    MINICONDA_URL=$DEFAULT_MINICONDA_URL-x86_64.sh; \
    elif [ "$ARCH" = "aarch64" ]; then \
    MINICONDA_URL=$DEFAULT_MINICONDA_URL-aarch64.sh; \
    else \
    echo "Unsupported architecture: $ARCH"; exit 1; \
    fi && \
    wget --quiet $MINICONDA_URL -O /tmp/miniconda.sh && \
    /bin/bash /tmp/miniconda.sh -b -p /opt/conda && \
    rm /tmp/miniconda.sh

# Add conda to PATH
ENV PATH="/opt/conda/bin:$PATH"

RUN conda install python=$PYTHON_VERSION

# Update pip and setuptools in the base environment
RUN conda clean -y --all && \
    pip install --upgrade pip setuptools

RUN conda info